### ISSUE TITLE
components to be read from toml file

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/simulator#9]
allow parameterizing components in the toml config

**Comment by RafyAmgadBenjamin** [comment]
- We have refactored the code and update the TOML file structure to be able to load all hardware and its components 
- we faced an issue related to TOML Parsing

**Comment by xmonader** [comment]
It seems the TOML is bit more advanced for the current available TOML parsers https://github.com/crystal-community/toml.cr/issues/24 . The issue been communicated to manas

**Comment by RafyAmgadBenjamin** [comment]
#### Fixed 
we have used YAML instead of TOML due to the issue we have faced during TOML parsing 

#### the configuration including hardware configuration can be written through a YAML file

#### Commits
74a18c90560a50debe1f49283b34c20741bd737e
34f06381939861775012302366f6a424de7aefb3
fcb7af39917698501a5e4d9092f561d61b34a4d4
3730f5d566f61022c1ca91c1cb6261971330ce52
e11ebe12b64eead58d03cffbc03370a97383abb8
e11ebe12b64eead58d03cffbc03370a97383abb8
591aeedc0910c83b052e4f609550240514912f17
e08e4cae268b0b37799bf354b0c7791ffc913123
ed765f8e256141b22402c3dc6abdb1a9a352cc46

**Comment by abom** [comment]
Still needs proper verification?
